### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by fibo** [utrustdev/utrust-ts-library#24]
I am trying `@utrustdev/utrust-ts-library` version `1.0.4`.

on sandobox environment, with parameters

```
const order = {
  reference: '1234',
  amount: { total: '60.00', currency: 'EUR' },
  return_urls: { return_url: 'https://app.ggbot2.com/settings#billing' },
  line_items: []
} 
const customer = {
  first_name: 'satoshi',
  last_name: 'nakamoto',
  email: 'email@example.com',
  country: 'IT'
}

```

I am getting "Request failed with status code 400", any hint?

**Comment by TondaHack** [comment]
If it's 400, the server should also return the error message pointing out what is wrong in what field. 

Based on our [docs](https://docs.api.utrust.com/#tag/Store-Order/operation/createOrder), it seems that `line_items` is required. It shouldn't be an empty list. Please, check the error message of the API endpoint to determine the issue.

**Comment by fibo** [comment]
Thanks for your answer.

I also tried with line_items before. I think the issue I got actually is `first_name` and `last_name` are not required in `Customer` type but they are in the API.
